### ISSUE TITLE
Initial set of UI improvements

### ISSUE THREAD

**Issue by hdoupe** [comp-org/comp#39]
@MattHJensen has provided a list of UI improvements:

- [ ] Stretch top paragraphs to the same width as the input section below.
- [ ] Align all buttons in the left column at right and left, to the same width. - Center left button text.
- [ ] Put a single (maybe fat) vertical line between left column and right column. that goes down from bottom of the top paragraphs.
- [ ] Move meta parameters back to the left column.
- [x] Call "Input Sections" -> "Model Parameters"
- [x] Move "Reset Parameters" below "Run Simulation"
- [x] I think there is a light shadow box behind each of the parameter sections. Make that pop out a lot more, or remove it.
- [ ] On the right hand side, align all text, except data forms can be slightly offset to the right.
- [ ] Pop out the entire left and right columns of the model inputs section in a light but noticably color box.
- [x] Make it obvious that links are links.
- [ ] Fix column names/alignment in Baseball app
- [ ] Default value presentation: should info be smaller? should it only appear after the default placeholder value has been removed?
- [ ] The button for collapsing/uncollapsing the sections should either correspond to the action (minus sign for collapse/plus for uncollapse) or it should be agnostic.
- [ ] Meta parameters should have info boxes

Am I missing anything? If I am or if you have any other ideas for how things could be made better, feel free to drop them in this issue. I'll see how far I can get with these today.

**Comment by hdoupe** [comment]
- [ ] Resize meta parameter input box and button.

**Comment by MattHJensen** [comment]
- [ ] I always found TaxBrain to be more usable and engaging before we collapsed the sections by default, because then it was much easier to scroll past everything and see what you are dealing with, and users who knew which parameter they wanted could do a cmd-f to find it. I'm somewhat inclined to uncollapse everything by default. 

> Put a single (maybe fat) vertical line between left column and right column. that goes down from bottom of the top paragraphs.

- [ ] Not sure we need this one anymore with the left buttons uniform width. Doesn't hurt to try, but maybe not necessary. 

> Move meta parameters back to the left column.

I'm ok where these are now, especially if we add a "Meta" button on the left, and I think we can just call them "Meta on the right

> Call "Input Sections" -> "Model Parameters" 

I'm now inclined to call "Input Sections" -> "Inputs", under which we'd have "Meta" and "Matchups", so that model users don't necessarily need to deal with the term "parameters."

**Comment by hdoupe** [comment]
After some re-tinkering with the inputs page--specifically the sidebar/app text and inputs, here's how things look:

![screenshot from 2019-01-05 16-09-21](https://user-images.githubusercontent.com/9206065/50729248-ace8f380-1104-11e9-9cfb-1949a5adf4c9.png)

![screenshot from 2019-01-05 16-14-51](https://user-images.githubusercontent.com/9206065/50729283-38628480-1105-11e9-9c24-f37b6d1cc7fb.png)

I think the layout is much nicer now. The text is lined up with the inputs and the navbar stays at the top of the screen when scrolling. I've been having some trouble getting the sidebar to stay in place while scrolling, but I'll keep working on that problem.

**Comment by hdoupe** [comment]
@MattHJensen what's your reasoning for moving the "Meta Parameters" section to the sidebar?

**Comment by MattHJensen** [comment]
I am closing this issue in favor of a new GUI discussion, since a lot has changed since it was opened on jan 4.
